#!/bin/bash

if [ $XDG_SESSION_TYPE == 'wayland' ]; then
  /bin/sleep 0.1 && /bin/dbus-send --session --print-reply --dest=org.kde.kglobalaccel  /component/org_kde_powerdevil org.kde.kglobalaccel.Component.invokeShortcut string:'Turn Off Screen'
else
  xset dpms force off
fi
